# Pytorch Tutorial 1

In [1]:
import torch
import numpy as np

### Dataset & DataLoader

In [43]:
from torch.utils.data import Dataset, DataLoader

In [44]:
class MyDataset(Dataset):
  def __init__(self, file):
    self.data = file

  def __getitem__(self, index):
    return self.data[index]

  def __len__(self):
    return len(self.data)

In [45]:
file = torch.rand([1000, 32])

In [47]:
dataset = MyDataset(file)

In [48]:
dataset.data.shape

torch.Size([1000, 32])

In [49]:
dataset[0]

tensor([0.1099, 0.7090, 0.4163, 0.1079, 0.7583, 0.4634, 0.6594, 0.7747, 0.5650,
        0.4925, 0.3136, 0.3071, 0.0762, 0.1251, 0.2516, 0.8053, 0.7067, 0.4802,
        0.0702, 0.0684, 0.2995, 0.6982, 0.0024, 0.2056, 0.2078, 0.8000, 0.5338,
        0.4538, 0.2912, 0.0093, 0.4647, 0.3792])

In [50]:
len(dataset)

1000

In [53]:
dataloader = DataLoader(dataset, batch_size=5, shuffle=True)

## Tensor

### Creating Tensors

In [2]:
# creating tensors
x = torch.tensor([[1, -1], [-1, 1]])
x = torch.from_numpy(np.array([[1, -1], [-1, 1]]))
x

tensor([[ 1, -1],
        [-1,  1]])

In [3]:
# tensor of constant zeros & ones
# input is shape
x = torch.zeros([2, 2])
x

tensor([[0., 0.],
        [0., 0.]])

In [4]:
x = torch.ones([1,2,5])
x

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

### Common Operations

In [5]:
# summation
x.sum()

tensor(10.)

In [6]:
# mean
x.mean()

tensor(1.)

In [7]:
# power
x.pow(2)

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

#### Transpose
transpose two specified dimensions

In [8]:
x = torch.zeros([2,3])
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
x.shape

torch.Size([2, 3])

In [10]:
x = x.transpose(0,1)
x

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [11]:
x.shape

torch.Size([3, 2])

#### Squeeze
remove the specified dimension with length is 1

In [12]:
x = torch.zeros([1,2,3])
x

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

In [13]:
x.shape

torch.Size([1, 2, 3])

In [14]:
x = x.squeeze(0)

In [15]:
x.shape

torch.Size([2, 3])

#### Unsqueeze
expand a new dimension

In [16]:
x = torch.zeros([2, 3])
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [17]:
x.shape

torch.Size([2, 3])

In [18]:
x = x.unsqueeze(1)

In [19]:
x.shape

torch.Size([2, 1, 3])

#### Cat
concatenate multiple tensors

In [20]:
x = torch.zeros([2, 1, 3])
y = torch.zeros([2, 3, 3])
z = torch.zeros([2, 2, 3])

In [21]:
w = torch.cat([x, y, z], dim=1)
w.shape

torch.Size([2, 6, 3])

### Device(GPU)

In [22]:
torch.cuda.is_available()

True

### Gradien Calculation

In [23]:
x = torch.tensor([[1., 0.], [-1., 1.]], requires_grad=True)

In [28]:
z = x.pow(2).sum()
z

tensor(3., grad_fn=<SumBackward0>)

In [25]:
z.backward()

In [26]:
x.grad

tensor([[ 2.,  0.],
        [-2.,  2.]])

## Training & Testing Neural Networks – in Pytorch

### Network Parameters

#### Linear Layer (Fully-connected Layer)

In [29]:
layer = torch.nn.Linear(32, 64)

In [30]:
layer.weight.shape

torch.Size([64, 32])

In [31]:
layer.bias.shape

torch.Size([64])

#### Build your own neural network

In [32]:
import torch.nn as nn

In [69]:
class MyModel(nn.Module):
  def __init__(self):
    super(MyModel, self).__init__()
    self.net = nn.Sequential(
        nn.Linear(10, 32),
        nn.Sigmoid(),
        nn.Linear(32, 1)
    )

  def forward(self, x):
    return self.net(x)

In [34]:
class MyModel(nn.Module):
  def __init__(self):
    super(MyModel, self).__init__()
    self.layer1 = nn.Linear(10, 32)
    self.layer2 = nn.Sigmoid(),
    self.layer3 = nn.Linear(32, 1)

  def forward(self, x):
    out = self.layer1(x)
    out = self.layer2(out)
    out = self.layer3(out)
    return out

### Loss Functions

In [35]:
# mean squared error
criterion = nn.MSELoss()

In [36]:
# cross entropy
criteion = nn.CrossEntropyLoss()

In [37]:
# loss = criterion(model_output, expected_value)

### Neural Network Training Setup

In [39]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [78]:
file = torch.rand([1000, 10])

In [92]:
target = torch.rand([1000, 1])
target[:5]

tensor([[0.3719],
        [0.7129],
        [0.7720],
        [0.7079],
        [0.3593]])

In [84]:
class MyDataset(Dataset):
  def __init__(self, file, target):
    self.data = file
    self.target = target

  def __getitem__(self, index):
    return self.data[index], self.target[index]

  def __len__(self):
    return len(self.data)

In [93]:
dataset = MyDataset(file, target)
dataset[0]

(tensor([0.0027, 0.5356, 0.3574, 0.6433, 0.4401, 0.9757, 0.2687, 0.5426, 0.0875,
         0.2855]),
 tensor([0.3719]))

In [95]:
dataset = MyDataset(file, target)  # read data via MyDataset
tr_set = DataLoader(dataset, batch_size=16, shuffle=True)  # put dataset into Dataloader

model = MyModel().to(device)  # construct model and move to device (cpu/cuda)

criterion = nn.MSELoss()  # set loss function
optimizer = torch.optim.SGD(model.parameters(), lr=0.1)  # set optimizer

In [56]:
n_epochs = 10

In [96]:
for epoch in range(n_epochs):  # iterate n_epochs
  model.train()  # set model to train mode

  for x, y in tr_set:  # iterate through the dataloader
    optimizer.zero_grad()  # set gradient to zero
    x, y = x.to(device), y.to(device)  # move data to device (cpu/cuda)
    pred = model(x)  # forward pass (compute output)
    loss = criterion(pred, y)  # compute loss
    loss.backward()  # compute gradient (backpropagation)
    optimizer.step()  # update model with optimizer

### Neural Network Valudation Loop

In [102]:
dv_set = DataLoader(dataset, batch_size=16, shuffle=False)

In [103]:
model.eval()  # set model to evaluation mode
total_loss = 0

for x, y in dv_set:  # iterate through the dataloader
  x, y = x.to(device), y.to(device)  # move data to device (cpu/cuda)

  with torch.no_grad():  # disable gradient calculation
    pred = model(x)  # forward pass (compute output)
    loss = criterion(pred, y)  # compute loss

  total_loss += loss.cpu().item()*len(x)  # accumulate loss
  avg_loss = total_loss / len(dv_set.dataset)  # compute averaged loss

In [105]:
print(f"avg loss is {avg_loss:.6f}")

avg loss is 0.095253


### Neural Network Testing Loop

In [109]:
tt_set = DataLoader(dataset.data, shuffle=False)

In [110]:
model.eval()  # set model to evaluation mode
preds = []

for x in tt_set:  # iterate through the dataloader
  x = x.to(device)  # move data to device (cpu/cuda)

  with torch.no_grad():  # disable gradient calculation
    pred = model(x)  # forward pass (compute output)
    preds.append(pred.cpu())  # collect prediction

In [112]:
preds[:5]

[tensor([[0.5933]]),
 tensor([[0.6030]]),
 tensor([[0.6021]]),
 tensor([[0.5999]]),
 tensor([[0.5946]])]

In [113]:
torch.save(model.state_dict(), "pytorch_tutorial_model.pt")

In [114]:
ckpt = torch.load("pytorch_tutorial_model.pt")
model.load_state_dict(ckpt)

<All keys matched successfully>

# Pytorch Tutorial 2

In [13]:
import torch
import numpy as np

In [14]:
input = torch.tensor([[1, 2, 3], [5, 6, 4]])
input

tensor([[1, 2, 3],
        [5, 6, 4]])

In [4]:
torch.max(input)

tensor(6)

In [8]:
torch.max(input, dim=1, keepdim=False, out=None)

torch.return_types.max(
values=tensor([3, 6]),
indices=tensor([2, 1]))

In [15]:
other = torch.tensor([[2, 4, 6], [1, 3, 5]])

In [10]:
torch.max(input, other)

tensor([[2, 4, 6],
        [5, 6, 5]])

## Common Error

### Tensor on Different Device to Model

In [23]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [16]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [19]:
model = torch.nn.Linear(5, 1).to(device)
x = torch.randn(5).to("cpu")
y = model(x)

In [24]:
x = torch.randn(5).to(device)
y = model(x)
y.shape

torch.Size([1])

### Mismatched Dimensions

In [25]:
x = torch.randn(4, 5)
y = torch.randn(5, 4)

In [30]:
z = x + y

RuntimeError: The size of tensor a (5) must match the size of tensor b (4) at non-singleton dimension 1

=> the shape of a tensor is incorrect, use `transpose`, `squeeze`, `unsqueeze` to align the dimensions

In [31]:
y = y.transpose(0, 1)

In [32]:
z = x + y
print(z.shape)

torch.Size([4, 5])


### Cuda Out of Memory

In [33]:
import torch
import torchvision.models as models

In [ ]:
resnet18 = models.resnet18().to(device)  # Neural Networks for Image
data = torch.randn(512, 3, 244, 244)  # create fake data (512 images)
out = resnet18(data.to(device))  # use Data as Input and Feed to
print(out)

### Mismatched Tensor Type

In [2]:
import torch
import torch.nn as nn
L = nn.CrossEntropyLoss()
outs = torch.randn(5, 5)
labels = torch.Tensor([1, 2, 3, 4, 0])
lossval = L(outs, labels)  # calculate CrossEntropyLoss between outs and labels

RuntimeError: expected scalar type Long but found Float

In [3]:
labels = labels.long()
lossval = L(outs, labels)
print(lossval)

tensor(1.7446)
